--- arch/arm/mach-msm/Makefile	2013-04-20 02:33:28.183486808 -0700
+++ arch/arm/mach-msm/Makefile	2013-04-20 02:30:35.365042796 -0700
@@ -114,13 +115,20 @@
 ifdef CONFIG_ARCH_MSM8960
 	obj-y += emmc_partitions.o
 endif
+ifdef CONFIG_MACH_PICO
+        obj-y += nand_partitions.o
+endif
 
 ifeq ($(CONFIG_ARCH_MSM7X30_SMD),y)
 obj-$(CONFIG_ARCH_MSM7X30_SMD) += 7x30-smd/
 else # Else CONFIG_ARCH_MSM7X30_SMD
 obj-y += modem_notifier.o
 obj-$(CONFIG_MSM_SMD_LOGGING) += smem_log.o
+ifeq ($(CONFIG_ARCH_MSM7X27A),y)
+obj-$(CONFIG_MSM_SMD) += smd.o smd_7x2x_debug.o
+else # Else CONFIG_ARCH_MSM7X27A
 obj-$(CONFIG_MSM_SMD) += smd.o smd_debug.o
+endif # End CONFIG_ARCH_MSM7X27A
 obj-$(CONFIG_MSM_SMD_TTY) += smd_tty.o
 obj-$(CONFIG_MSM_SMD_QMI) += smd_qmi.o
 obj-$(CONFIG_MSM_SMD_PKT) += smd_pkt.o
@@ -151,16 +159,21 @@
 obj-$(CONFIG_MSM_IPC_ROUTER)+= ipc_socket.o
 obj-$(CONFIG_MSM_DALRPC) += dal.o
 obj-$(CONFIG_MSM_DALRPC_TEST) += dal_remotetest.o
-obj-$(CONFIG_ARCH_MSM7X30) += dal_axi.o
-obj-$(CONFIG_ARCH_MSM7X27A) += dal_axi.o
+#obj-$(CONFIG_ARCH_MSM7X30) += dal_axi.o
+obj-$(CONFIG_ARCH_MSM7X30) += dal_axi.o htc_drm.o htc_sdservice.o
+obj-$(CONFIG_ARCH_MSM7X27A) += dal_axi.o htc_drm.o htc_sdservice.o
 obj-$(CONFIG_MSM_ADSP) += qdsp5/
 #obj-$(CONFIG_MSM7KV2_AUDIO) += qdsp5v2/
 obj-$(CONFIG_MSM7KV2_AUDIO) += qdsp5v2_2x/
+obj-$(CONFIG_MSM7KV2_1X_AUDIO) += qdsp5v2_1x/
 obj-$(CONFIG_MSM7KV2_AUDIO) += htc_acoustic_7x30.o htc_acdb_7x30.o
+obj-$(CONFIG_MSM7KV2_1X_AUDIO) += htc_acoustic_7x30.o htc_acdb_7x30.o
 
 obj-$(CONFIG_MSM_QDSP6) += qdsp6/
-obj-$(CONFIG_MSM8X60_AUDIO) += qdsp6v2_1x/
+obj-$(CONFIG_MSM8X60_AUDIO) += qdsp6v2/
 obj-$(CONFIG_MSM_AUDIO_QDSP6) += qdsp6v2/
+obj-$(CONFIG_MSM_AUDIO_QDSP6V2) += qdsp6v2/
+
 obj-$(CONFIG_MSM_HW3D) += hw3d.o
 ifdef CONFIG_PM
 	obj-$(CONFIG_ARCH_MSM8960) += pm-8x60.o
@@ -249,19 +262,24 @@
 obj-$(CONFIG_MACH_GOLFU) += display/board-golfu-panel.o
 obj-$(CONFIG_MACH_GOLFU) += board-golfu-keypad.o
 obj-$(CONFIG_MACH_GOLFU) += board-golfu-mmc.o
-obj-$(CONFIG_MACH_GOLFU) += htc_bdaddress.o
-obj-$(CONFIG_MACH_PRIMODD) += board-primodd.o devices-msm7x27a.o devices_htc.o emmc_partitions.o
+obj-$(CONFIG_MACH_GOLFU) += board-golfu-wifi.o htc_wifi_nvs.o htc_util_7x2x.o
+obj-$(CONFIG_MACH_GOLFU) += htc_bdaddress.o board-bahama.o
+obj-$(CONFIG_MACH_PRIMODD) += board-primodd.o devices-msm7x27a.o devices_htc.o emmc_partitions.o board-primodd-gpio.o  htc_util_7x2x.o
 obj-$(CONFIG_MACH_PRIMODD) += display/board-primodd-panel.o
 obj-$(CONFIG_MACH_PRIMODD) += board-primodd-keypad.o
-obj-$(CONFIG_MACH_PRIMODD) += board-primodd-mmc.o board-primodd-wifi.o
+obj-$(CONFIG_MACH_PRIMODD) += board-primodd-mmc.o board-primodd-wifi.o htc_wifi_nvs.o
 obj-$(CONFIG_MACH_PRIMODD) += board-primodd-gsm-radio.o
+obj-$(CONFIG_MACH_PRIMODD) += board-primodd-audio.o
 obj-$(CONFIG_MACH_PRIMODD) += audiogpio.o
 obj-$(CONFIG_MACH_PRIMODD) += board-primodd-rfkill.o htc_fast_clk_7k.o
 obj-$(CONFIG_MACH_PRIMODS) += board-primods.o devices-msm7x27a.o devices_htc.o emmc_partitions.o
 obj-$(CONFIG_MACH_PRIMODS) += display/board-primods-panel.o
 obj-$(CONFIG_MACH_PRIMODS) += board-primods-keypad.o
 obj-$(CONFIG_MACH_PRIMODS) += board-primods-mmc.o
-obj-$(CONFIG_MACH_PRIMODS) += board-primods-wifi.o htc_wifi_nvs.o htc_fast_clk_7k.o board-primods-rfkill.o
+obj-$(CONFIG_MACH_PRIMODS) += board-primods-wifi.o htc_wifi_nvs.o htc_fast_clk_7k.o board-primods-rfkill.o htc_util_7x2x.o
+obj-$(CONFIG_MACH_PRIMODS) += board-primods-audio.o
+obj-$(CONFIG_MACH_PRIMODS) += htc_simhotswap_slot1.o
+obj-$(CONFIG_MACH_PRIMODS) += htc_simhotswap_slot2.o
 obj-$(CONFIG_ARCH_MSM7X30) += devices-msm7x30.o memory_topology.o devices_htc.o emmc_partitions.o msm_vibrator.o
 obj-$(CONFIG_ARCH_MSM7X30) += clock-local.o clock-7x30.o acpuclock-7x30.o htc_awb_cal.o
 obj-$(CONFIG_MACH_MSM7X25_SURF) += board-msm7x27.o devices-msm7x25.o
@@ -454,6 +496,25 @@
 obj-$(CONFIG_MACH_BLISS) += display/bliss-panel.o board-bliss-audio.o
 obj-$(CONFIG_MACH_BLISS) += htc_sleep_clk.o htc_fast_clk_7k.o board-bliss-rfkill.o
 obj-$(CONFIG_MACH_BLISS) += htc_bdaddress.o
+obj-$(CONFIG_MACH_SPADE) += board-spade.o
+obj-$(CONFIG_MACH_SPADE) += board-spade-microp.o
+obj-$(CONFIG_MACH_SPADE) += board-spade-keypad.o board-spade-audio.o
+obj-$(CONFIG_MACH_SPADE) += board-spade-mmc.o board-spade-wifi.o
+obj-$(CONFIG_MACH_SPADE) += display/spade-panel.o
+obj-$(CONFIG_MACH_SPADE) += htc_sleep_clk.o htc_fast_clk_7k.o
+obj-$(CONFIG_MACH_SPADE) += htc_bdaddress.o board-spade-rfkill.o
+obj-$(CONFIG_MACH_SAGA) += board-saga.o
+obj-$(CONFIG_MACH_SAGA) += board-saga-keypad.o
+obj-$(CONFIG_MACH_SAGA) += board-saga-mmc.o board-saga-wifi.o
+obj-$(CONFIG_MACH_SAGA) += display/saga-panel.o board-saga-audio.o display/panel-sonywvga-s6d16a0x21-7x30.o
+obj-$(CONFIG_MACH_SAGA) += htc_sleep_clk.o htc_fast_clk_7k.o
+obj-$(CONFIG_MACH_SAGA) += htc_bdaddress.o board-saga-rfkill.o
+obj-$(CONFIG_MACH_MECHA) += board-mecha.o
+obj-$(CONFIG_MACH_MECHA) += board-mecha-keypad.o
+obj-$(CONFIG_MACH_MECHA)+= board-mecha-mmc.o board-mecha-wifi.o
+obj-$(CONFIG_MACH_MECHA) += display/mecha-panel.o board-mecha-audio.o
+obj-$(CONFIG_MACH_MECHA) += htc_sleep_clk.o htc_fast_clk_7k.o
+obj-$(CONFIG_MACH_MECHA) += htc_bdaddress.o board-mecha-rfkill.o
 obj-$(CONFIG_MACH_PRIMOU) += board-primou.o
 obj-$(CONFIG_MACH_PRIMOU) += display/primou-panel.o board-primou-audio.o
 obj-$(CONFIG_MACH_PRIMOU) += board-primou-keypad.o
@@ -489,7 +557,7 @@
 obj-$(CONFIG_MACH_KINGDOM) += board-kingdom-mmc.o board-kingdom-wifi.o
 endif
 
-obj-$(CONFIG_MACH_KINGDOM) += htc_bdaddress.o
+obj-$(CONFIG_MACH_KINGDOM) += htc_bdaddress.o board-kingdom-rfkill.o
 
 CFLAGS_msm_vibrator.o += -Idrivers/staging/android
 
